---
- name: Checking host details and status
  hosts: all
  gather_facts: True
  tasks:
    - debug: var=ansible_all_ipv4_addresses
    - debug: var=ansible_hostname
    - debug: var=ansible_distribution
    - debug: var=ansible_distribution_version
    - debug: var=ansible_distribution_major_version
    - debug: var=ansible_memtotal_mb

