---
- name: Install packages based on matching criteria
  hosts: all
  tasks:
    - name: Install apache on Ubuntu
      when: ansible_distribution == "Ubuntu"
      package:
        name: apache2
        state: latest
      become: true
      register: result
#    - debug: var=result
    - name: Install apache on Redhat
      when: ansible_distribution == "RedHat"
      package:
        name: httpd
        state: latest
      register: result
#    - debug: var=result
