---
- name: Install packages based on matching criteria
  hosts: all
  tasks:
    - name: Install apche
      when: ansible_hostname == "node1"
      package:
        name: httpd
        state: latest
      register: result
    - debug: var=result
    - name: Install zip
      when: ansible_hostname == "node2"
      package:
        name: zip
        state: latest
      register: result
    - debug: var=result
