---
- name: Install multiple packages
  hosts: all
  tasks:
    - name: Install packages on centos/rhel
      package: name={{item}} state=present
      with_items:
        - vim
        - httpd
        - zip

- name: Install multiple packages
  hosts: all
  vars:
    packages: 
      - vim
      - httpd
      - zip
  tasks:
    - name: Install packages on centos/rhel
      package: name={{item}} state=present
      with_items: "{{packages}}"

