---
- name: Installing Ansible AWX in CENTOS 7
  hosts: all
  tasks:
#  - name: Disable firewalld
#    service: 
#     name=firewalld 
#     state=stopped
#     enabled=False
  - name: Disable Selinux
    lineinfile:
     path: /etc/sysconfig/selinux
     regexp: '^SELINUX='
     line: 'SELINUX=disabled'
  - name: Disable IPV6
    lineinfile: "dest=/etc/sysctl.d/ipv6.conf line='net.ipv6.conf.all.disable_ipv6 = 1' create=yes"
    notify:
    - rmmodipv6
      when: ansible_os_family == 'RedHat'
  - name: Restart server
    command: /sbin/shutdown -r +1
    async: 0
    poll: 0
    ignore_errors: true
