---
- name: Installing Ansible AWX in CENTOS 7
  hosts: all
  tasks:
  - name: Disable firewalld
    service: name=firewalld state=stopped enabled=False
    when: ansible_distribution == 'RedHat' and ansible_distribution_major_version == '7'
  - name: Disable IPables
    service: name=iptables state=stopped enabled=no
    when: ansible_distribution == 'RedHat' and ansible_distribution_major_version == '6'
  - name: Disable Selinux
    lineinfile:
     path: /etc/sysconfig/selinux
     regexp: '^SELINUX='
     line: 'SELINUX=disabled'
  - name: Disable IPV6
    lineinfile: "dest=/etc/sysctl.d/ipv6.conf line='net.ipv6.conf.all.disable_ipv6 = 1' create=yes"
#  - name: Restart server
#    command: /sbin/shutdown -r +1
#    async: 0
#    poll: 0
#    ignore_errors: true
#  - name: Waiting for server to come back
#    local_action: wait_for host={{ ansible_ssh_host }} state=started
  - name: Install and configuring epel-release repository
    yum: name=epel-release state=latest
  - name: Install pre-requiste rpm packages for Ansible AWX
    yum: pkg={{item}} state=present exclude=dcoker-io*
    with_items:
     - git
     - gettext
     - ansible
     - docker
     - nodejs
     - npm
     - gcc-c++
     - bzip2
     - python-docker-py
  - name: Starting Docker service
    service: name=docker state=started enabled=True
  - name: Clone awx.git to Remote system
    git:
     repo: 'https://github.com/ansible/awx.git'
     dest: /tmp
    
