---
- name: Installing Ansible AWX in CENTOS 7
  hosts: all
  tasks:
  - name: Disable firewalld
    service: 
     name=firewalld 
     state=stopped
     enabled=False
  - name: Disable Selinux
    selinux: 
     state=disabled
  - name: Restart server
    command: /sbin/shutdown -r +1
    async: 0
    poll: 0
    ignore_errors: true
