- name: Task to boot a system using an ISO from an HP iLO interface only if the system is an HP server
  hosts: all
  tasks:
   hpilo_boot:
    media: cdrom
    image: http://distro.ibiblio.org/puppylinux/puppy-4.3.1/pup-431.iso
