---
- name: internet services
  hosts: all
  gather_facts: True
  connection: local
  tasks:
    - debug: var=ansible_all_ipv4_addresses
    - debug: var=ansible_default_ipv4.address
    - debug: var=ansible_hostname
